config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'home#show'

  get 'home/show'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get 'location' => 'locations#edit'
  post 'location' => 'locations#create'
  patch 'location' => 'locations#update'
  resolve('Location') { [:location] }

  get 'options' => 'user_options#edit'
  post 'options' => 'user_options#create'
  patch 'options' => 'user_options#update'
  resolve('UserOptions') { [:user_options] }

  get 'community' => 'community#show'
  post 'email_community' => 'community#email_community', as: :email_community

  get 'terms' => 'terms#show'

  get 'contact_us' => 'contact_us#new'
  post 'contact_us' => 'contact_us#create'

  get 'unsubscribe' => 'prototype_users#unsubscribe'

  scope :api do
    post 'prototype_users' => 'api/prototype_users#create'
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def show
    return unless user_signed_in?

    redirect_to community_path
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/index.html.erb
<div>
  <h1>Simply Always Awake Community Locator</h1>
</div>

<% if user_signed_in? %>
  <%= link_to "Edit location", location_path, class: "rounded-lg m-2 py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
  <div>
    <%= link_to 'Sign out', destroy_user_session_path, data: { "turbo-method": :delete }, class: "rounded-lg py-3 m-2 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% else %>
  <div class="rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium">
    <%= link_to "Sign up", new_user_registration_path %>
  </div>
  <div class="rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium">
    <%= link_to 'Sign in', new_user_session_path %>
  </div>
<% end %>

app/views/home/show.html.erb
<%= render "application/flash_messages" %>
<div class="bg-white mt-10">
  <div class="mx-auto max-w-7xl px-6 pt-24 pb-8 sm:pt-32 lg:px-8">
    <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Simply Always Awake<br>Community Locator</h2>
    <p class="mt-6 text-lg leading-8 text-gray-600">Find people near you who are waking up</p>
    <div class="mt-6 flex items-center gap-x-6">
      <%= link_to 'Get started', new_user_registration_path, class: 'rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600' %>
    </div>
    <div class="mt-6 flex items-center gap-x-3">
      <p>Already have an account?</p>
      <%= link_to 'Sign in', new_user_session_path, class: 'rounded bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50' %>
    </div>
  </div>
</div>