config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'home#show'

  get 'home/show'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get 'location' => 'locations#edit'
  post 'location' => 'locations#create'
  patch 'location' => 'locations#update'
  resolve('Location') { [:location] }

  get 'options' => 'user_options#edit'
  post 'options' => 'user_options#create'
  patch 'options' => 'user_options#update'
  resolve('UserOptions') { [:user_options] }

  get 'community' => 'community#show'
  post 'email_community' => 'community#email_community', as: :email_community

  get 'terms' => 'terms#show'

  get 'contact_us' => 'contact_us#new'
  post 'contact_us' => 'contact_us#create'

  get 'unsubscribe' => 'prototype_users#unsubscribe'

  scope :api do
    post 'prototype_users' => 'api/prototype_users#create'
  end
end

app/controllers/community_controller.rb
# frozen_string_literal: true

class CommunityController < ApplicationController
  include Pagy::Backend

  before_action :authenticate_user!
  before_action :validate_profile!
  before_action :validate_location!
  before_action :validate_options!

  after_action :save_current_nearby_users,
               only: %i[show],
               unless: -> { current_user.has_seen_community? }

  def show
    @location = current_user.location
    @pagy, @community = pagy(Community.for(current_user))
    @range = current_user.user_options.community_range
    render(@community.empty? ? 'empty' : 'show')
  end

  def email_community
    @location = current_user.location
    return unless @location

    @community = Community.for(current_user)
    UserMailer
      .with(user: current_user, community: @community)
      .my_community(current_user, @community)
      .deliver_now
    redirect_to community_path, notice: 'Email sent' # rubocop:disable Rails/I18nLocaleTexts
  end

  private

  def validate_profile!
    return unless current_user.name.nil?

    redirect_to edit_user_registration_path(nil, welcome: true)
  end

  def validate_location!
    return unless current_user.location.nil?

    redirect_to location_path
  end

  def validate_options!
    return unless current_user.user_options.nil?

    redirect_to options_path
  end

  def save_current_nearby_users
    Community.new(current_user).save_current_nearby_users
    current_user.update(has_seen_community: true)
  end
end

app/helpers/community_helper.rb
# frozen_string_literal: true

module CommunityHelper
  include Pagy::Frontend
end

app/views/community/_list.html.erb
<div>
  <ul>
    <% @community.each do |user| %>      
      <li>
        <ul class="mt-6">
          <li class="font-bold"><%= display_name(user) %></li>
          <li class="ml-4"><%= short_address(user.location) %></li>
          <li class="ml-4"><%= user.email %></li>
        </ul>
      </li>
    <% end %>
  </ul>
</div>

app/views/community/empty.html.erb
<div class="text-center">
  <h3 class="mt-2 text-sm font-semibold text-gray-900">No members within <%= pluralize(@range, 'mile') %> of you.</h3>
  <% if @range < UserOptions::MAX_COMMUNITY_RANGE %>
    <p class="mt-1 text-sm text-gray-500">Come back later and see if anyone new in your area has registered, or consider increasing your range in Options.</p>
    <div class="mt-6">
      <%=
        link_to "Options",
        options_path,
        class: "inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600",
        data: {
          controller: "selected-nav",
          selected_nav_controller_value: controller_name,
          selected_nav_target: "item",
          item_id: "options"
        }
      %>
    </div>
  <% else %>
    <p class="mt-1 text-sm text-gray-500">Come back later and see if anyone new in your area has registered.</p>
  <% end %>

</div>

app/views/community/show.html.erb
<%- title "My Community" %>
<div class="px-4 sm:px-6 lg:px-8 pt-8">
  <div class="-mx-4 sm:-mx-0">
    <table class="min-w-full divide-y divide-gray-300">
      <thead>
        <tr>
          <th scope="col" class="hidden py-3.5 pr-3 text-left text-sm font-semibold text-gray-900 sm:table-cell">Name</th>
          <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 lg:table-cell">Location</th>
          <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 sm:table-cell">Email</th>
          <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 sm:table-cell">Telegram</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200 bg-white">
        <% @community.each do |user| %>
          <tr>
            <td class="w-full max-w-0 py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:w-auto sm:max-w-none sm:pl-0">
              <%= display_name(user) %>
              <dl class="font-normal lg:hidden">
                <dt class="sr-only">Location</dt>
                <dd class="mt-1 truncate text-gray-700"><%= short_address(user.location) %></dd>
                <dt class="sr-only sm:hidden">Email</dt>
                <dd class="mt-1 truncate text-gray-500 sm:hidden">Email: <%= user.email %></dd>
                <dd class="mt-1 truncate text-gray-500 sm:hidden">Telegram: <%= display_telegram(user) %></dd>
              </dl>
            </td>
            <td class="hidden px-3 py-4 text-sm text-gray-500 lg:table-cell"><%= short_address(user.location) %></td>
            <td class="hidden px-3 py-4 text-sm text-gray-500 sm:table-cell"><%= user.email %></td>
            <td class="hidden px-3 py-4 text-sm text-gray-500 sm:table-cell"><%= display_telegram(user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% if @pagy.count > 10 %>
      <div class="flex justify-center mt-2">
        <div class="mt-4 justify-center"><%== pagy_nav(@pagy) %></div>
      </div>
      <div class="flex justify-center mt-2 text-sm text-gray-500">
        <div class="justify-center"><%== pagy_info(@pagy) %></div>
      </div>
    <% end %>
  </div>
</div>
<div class="ml-4 sm:ml-0 px-4 sm:px-6 lg:px-8 pt-8">
  <div class="-mx-4 sm:-mx-0 min-w-full">
    <%= link_to "Email this list to me", email_community_path,data: { "turbo-method": :post }, class: "justify-center mt-4 rounded-md bg-indigo-500 text-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-indigo-600" %>
  </div>
</div>