config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'home#show'

  get 'home/show'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get 'location' => 'locations#edit'
  post 'location' => 'locations#create'
  patch 'location' => 'locations#update'
  resolve('Location') { [:location] }

  get 'options' => 'user_options#edit'
  post 'options' => 'user_options#create'
  patch 'options' => 'user_options#update'
  resolve('UserOptions') { [:user_options] }

  get 'community' => 'community#show'
  post 'email_community' => 'community#email_community', as: :email_community

  get 'terms' => 'terms#show'

  get 'contact_us' => 'contact_us#new'
  post 'contact_us' => 'contact_us#create'

  get 'unsubscribe' => 'prototype_users#unsubscribe'

  scope :api do
    post 'prototype_users' => 'api/prototype_users#create'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/views/application/_error_messages.html.erb
<% if object&.errors&.any? %>
  <div id="error_explanation" data-turbo-cache="false" class="bg-red-100 mt-10 sm:mx-auto sm:w-full sm:max-w-sm">  
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li class="flex items-center justify-between px-4 py-4">
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_flash_messages.html.erb
<% flash.each do |key, msg| %>
  <% if key == 'notice' %>
    <div class="rounded-md bg-green-50 p-4">
      <div class="flex">
        <div class="ml-3">
          <div class="text-sm text-green-700">
            <p><%= msg %></p>
          </div>
        </div>
      </div>
    </div>
  <% elsif key == 'alert' || key != 'timedout' %>
    <div class="rounded-md bg-yellow-50 p-4">
      <div class="flex">
        <div class="ml-3">
          <div class="text-sm text-yellow-700">
            <p><%= msg %></p>
          </div>
        </div>
      </div>
    </div>
  <% end  %>
<% end %>

app/views/application/_footer.html.erb
<footer>
  <div class="mx-auto max-w-7xl overflow-hidden px-6 py-20 sm:py-24 lg:px-8">
    <nav class="-mb-6 columns-2 sm:flex sm:justify-center sm:space-x-12" aria-label="Footer">

      <% if user_signed_in? %>
        <div class="pb-6">
          <%=
            link_to "Community",
            community_path,
            class: "text-sm leading-6 text-gray-600 hover:text-gray-900",
            data: {
              controller: "selected-nav",
              selected_nav_controller_value: controller_name,
              selected_nav_target: "item",
              item_id: "community"
            }
          %>
        </div>
      <% end %>

      <% if user_signed_in? %>
        <div class="pb-6">
          <%=
            link_to "Profile",
            edit_user_registration_path,
            class: "text-sm leading-6 text-gray-600 hover:text-gray-900",
            data: {
              controller: "selected-nav",
              selected_nav_controller_value: controller_name,
              selected_nav_target: "item",
              item_id: "profile"
            }
          %>
        </div>
      <% end %>

      <% if user_signed_in? %>
        <div class="pb-6">
          <%=
            link_to "Location",
            location_path,
            class: "text-sm leading-6 text-gray-600 hover:text-gray-900",
            data: {
              controller: "selected-nav",
              selected_nav_controller_value: controller_name,
              selected_nav_target: "item",
              item_id: "location"
            }
          %>
        </div>
      <% end %>

      <% if user_signed_in? %>
        <div class="pb-6">
          <%=
            link_to "Options",
            options_path,
            class: "text-sm leading-6 text-gray-600 hover:text-gray-900",
            data: {
              controller: "selected-nav",
              selected_nav_controller_value: controller_name,
              selected_nav_target: "item",
              item_id: "options"
            }
          %>
        </div>
      <% end %>

      <div class="pb-6">
        <a href="<%= contact_us_path %>" class="text-sm leading-6 text-gray-600 hover:text-gray-900">Contact Us</a>
      </div>

      <% if user_signed_in? %>
        <div class="pb-6">
          <%=
            link_to 'Sign out',
            destroy_user_session_path,
            data: {"turbo-method": :delete },
            class: "text-sm leading-6 text-gray-600 hover:text-gray-900"
          %>
        </div>
      <% end %>

    </nav>
    <p class="mt-10 text-center text-xs leading-5 text-gray-500">&copy; 2024 <a href="https://simplyalwaysawake.com/" class="font-semibold">Simply Always Awake</a>, LLC. All rights reserved.</p>
  </div>
</footer>

app/views/application/_header.html.erb
<nav class="border-b border-gray-200 bg-white">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="flex h-16 justify-between">
      <div class="flex">
        <div class="flex flex-shrink-0 items-center">
            <%= image_tag "logo.jpeg", class: "h-8 w-8 rounded-full", alt: "CommunityLocator" %>
        </div>
        <div class="hidden sm:-my-px sm:ml-6 sm:flex sm:space-x-8">
          <!-- Current: "border-indigo-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
          <%=
            link_to "Community",
            community_path,
            class: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium",
            data: {
              controller: "selected-nav",
              selected_nav_controller_value: controller_name,
              selected_nav_target: "item",
              item_id: "community"
            }
          %>

          <%=
            link_to "Profile",
            edit_user_registration_path,
            class: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium",
            data: {
              controller: "selected-nav",
              selected_nav_controller_value: controller_name,
              selected_nav_target: "item",
              item_id: "profile"
            }
          %>

          <%=
            link_to "Location",
            location_path,
            class: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium",
            data: {
              controller: "selected-nav",
              selected_nav_controller_value: controller_name,
              selected_nav_target: "item",
              item_id: "location"
            }
          %>

          <%=
            link_to "Options",
            options_path,
            class: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium",
            data: {
              controller: "selected-nav",
              selected_nav_controller_value: controller_name,
              selected_nav_target: "item",
              item_id: "options"
            }
          %>

        </div>
      </div>
      <div class="hidden sm:ml-6 sm:flex sm:items-center">
        <div class="ml-4 flex items-center md:ml-6">
            <%= link_to 'Sign out', destroy_user_session_path, data: { "turbo-method": :delete }, class: "text-gray-500 hover:text-gray-800 rounded-md px-3 py-2 text-sm font-medium" %>
        </div>
      </div>

      <div class="-mr-2 flex items-center sm:hidden">
        <!-- Mobile menu button -->
        <button data-action="menu#toggleMenu menu#toggleButton" type="button" class="relative inline-flex items-center justify-center rounded-md bg-white p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <!-- Menu open: "hidden", Menu closed: "block" -->
          <svg data-menu-target="closedButton" class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!-- Menu open: "block", Menu closed: "hidden" -->
          <svg data-menu-target="openButton" class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div data-menu-target="dropdown" class="hidden sm:hidden" id="mobile-menu">
    <div class="space-y-1 pb-3 pt-2">
      <!-- Current: "border-indigo-500 bg-indigo-50 text-indigo-700", Default: "border-transparent text-gray-600 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-800" -->
      <%=
        link_to "Community",
        community_path,
        class: "border-transparent text-gray-600 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-800 block border-l-4 py-2 pl-3 pr-4 text-base font-medium",
        data: {
          controller: "selected-nav",
          selected_nav_controller_value: controller_name,
          selected_nav_target: "item",
          item_id: "community"
        }
      %>

      <%=
        link_to "Profile",
        edit_user_registration_path,
        class: "border-transparent text-gray-600 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-800 block border-l-4 py-2 pl-3 pr-4 text-base font-medium",
        data: {
          controller: "selected-nav",
          selected_nav_controller_value: controller_name,
          selected_nav_target: "item",
          item_id: "profile"
        }
      %>

      <%=
        link_to "Location",
        location_path,
        class: "border-transparent text-gray-600 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-800 block border-l-4 py-2 pl-3 pr-4 text-base font-medium",
        data: {
          controller: "selected-nav",
          selected_nav_controller_value: controller_name,
          selected_nav_target: "item",
          item_id: "location"
        }
      %>

      <%=
        link_to "Options",
        options_path,
        class: "border-transparent text-gray-600 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-800 block border-l-4 py-2 pl-3 pr-4 text-base font-medium",
        data: {
          controller: "selected-nav",
          selected_nav_controller_value: controller_name,
          selected_nav_target: "item",
          item_id: "options"
        }
      %>


      <%=
        link_to 'Sign out',
        destroy_user_session_path,
        data: {"turbo-method": :delete },
        class: "border-transparent text-gray-500 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-800 block border-l-4 py-2 pl-3 pr-4 text-base font-medium"
      %>
    </div>
  </div>
</nav>

app/views/application/_main.html.erb
<main class="py-10">
  <header>
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold leading-tight tracking-tight text-gray-900"><%= content_for(:title) %></h1>
    </div>
  </header>
  <main>
  <div class="mt-2 mb-2 mx-auto max-w-7xl py-2 sm:py-2 lg:px-8">
    <%= render "application/flash_messages" %>
  </div>
  <div class="mx-auto max-w-7xl lg:px-8">
    <div class="rounded-lg bg-white px-5 pb-8 shadow-lg sm:px-6">
      <%= yield %>
    </div>
  </div>
</main>